/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Rax6Z93QvGwQM7zmXynKSOFbeVW03G9sKcaFcLiykU8IbZ5A3HuehKwQn6kiOxPVKjhl3rywCM5cadUIfeWoMg==
 */

// eslint:disable
// tslint:disable

import Photos, {Photos_InsertParameters} from './photos';
import Users, {Users_InsertParameters} from './users';

interface DatabaseSchema {
  photos: {record: Photos; insert: Photos_InsertParameters};
  users: {record: Users; insert: Users_InsertParameters};
}
export default DatabaseSchema;
