/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: N7hMdjZp9K7KGmFCSOiAXv1ap8n/UV5Cn7+zzYsTRmm8/FjMHdNKle/JDFtXAi8Wf7Gb7o0zJEbf7WlDdKGOZA==
 */

// eslint:disable
// tslint:disable

import Users from './users'

interface Photos {
  caption: string | null
  cdn_url: string
  id: number & {readonly __brand?: 'photos_id'}
  owner_user_id: Users['id']
}
export default Photos;

interface Photos_InsertParameters {
  caption?: string | null
  cdn_url: string
  id?: number & {readonly __brand?: 'photos_id'}
  owner_user_id: Users['id']
}
export {Photos_InsertParameters}
