/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1DKAKAJI2gHvCbBtcDZ49HmGKAZvYCMRF4Ao41Id4feV38KulHpU8AIGrNP8HTdTqDWmsxwA7XUKHDj6vNae+g==
 */

// eslint:disable
// tslint:disable

interface Users {
  age: number | null
  bio: string | null
  id: number & {readonly __brand?: 'users_id'}
  screen_name: string
}
export default Users;

interface Users_InsertParameters {
  age?: number | null
  bio?: string | null
  id?: number & {readonly __brand?: 'users_id'}
  screen_name: string
}
export {Users_InsertParameters}
