version: 2

refs:
  - &container
    docker:
      - image: node:12.16.3
        environment:
          PG_URL: 'postgres://test-user@localhost:5432/test-db'
          MYSQL_URL: 'mysql://test-user:password@localhost:3306/test-db'
      - image: postgres:10.6-alpine
        environment:
          POSTGRES_USER: test-user
          POSTGRES_DB: test-db
      - image: circleci/mysql:5.7.24
        environment:
          MYSQL_USER: test-user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test-db
    working_directory: ~/repo
  - &restore_cache
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "yarn.lock" }}
        - v1-dependencies-
  - &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "yarn.lock" }}
  - &npm_auth
    run:
      name: NPM Auth
      command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - &yarn_install
    run:
      name: Install Dependencies
      command: yarn install --frozen-lockfile
  - &build
    run:
      name: Build
      command: yarn build:all
  - &test
    run:
      name: Test
      command: yarn test --maxWorkers 2
  - &prettier
    run:
      name: Prettier (check yarn prettier:write has been run)
      command: yarn prettier:check

jobs:
  all:
    <<: *container
    steps:
      - checkout
      - *restore_cache
      - *npm_auth
      - *yarn_install
      - *save_cache
      - *prettier
      - *build
      - *test

  master:
    <<: *container
    steps:
      - checkout
      - *restore_cache
      - *npm_auth
      - *yarn_install
      - *save_cache
      - *prettier
      - *build
      - *test
      - run:
          name: Release
          command: npx rollingversions publish --dry-run

  publish:
    <<: *container
    steps:
      - checkout
      - *restore_cache
      - *npm_auth
      - *yarn_install
      - *build
      - run:
          name: Release
          command: npx rollingversions publish

workflows:
  version: 2
  all:
    jobs:
      - all:
          filters:
            branches:
              ignore:
                - master
  master:
    jobs:
      - master:
          context: common-env
          filters:
            branches:
              only: master

      - publish-approval:
          type: approval
          context: common-env
          requires:
            - master

      - publish:
          context: common-env
          filters:
            branches:
              only: master
          requires:
            - publish-approval

  nightly:
    triggers:
      - schedule:
          cron: '0 1 * * *'
          filters:
            branches:
              only: master
    jobs:
      - all:
          context: common-env
