// auto generated by test suite of pg-schema-introspect

enum PgDataTypeID {
  // === Boolean ===

  /**
   * boolean, 'true'/'false'
   */
  bool = 16,

  // === UserDefined ===

  /**
   * variable-length string, binary values escaped
   */
  bytea = 17,

  /**
   * (block, offset), physical location of tuple
   */
  tid = 27,

  /**
   * transaction id
   */
  xid = 28,

  /**
   * command identifier type, sequence in transaction id
   */
  cid = 29,

  json = 114,

  /**
   * XML content
   */
  xml = 142,

  /**
   * storage manager
   */
  smgr = 210,

  /**
   * XX:XX:XX:XX:XX:XX, MAC address
   */
  macaddr = 829,

  /**
   * XX:XX:XX:XX:XX:XX:XX:XX, MAC address
   */
  macaddr8 = 774,

  /**
   * access control list
   */
  aclitem = 1033,

  /**
   * reference to cursor (portal name)
   */
  refcursor = 1790,

  /**
   * UUID datatype
   */
  uuid = 2950,

  /**
   * PostgreSQL LSN datatype
   */
  pg_lsn = 3220,

  /**
   * text representation for text search
   */
  tsvector = 3614,

  /**
   * GiST index internal text representation for text search
   */
  gtsvector = 3642,

  /**
   * query representation for text search
   */
  tsquery = 3615,

  /**
   * Binary JSON
   */
  jsonb = 3802,

  /**
   * txid snapshot
   */
  txid_snapshot = 2970,

  // === String ===

  /**
   * single character
   */
  char = 18,

  /**
   * 63-byte type for storing system identifiers
   */
  name = 19,

  /**
   * variable-length string, no limit specified
   */
  text = 25,

  /**
   * string representing an internal node tree
   */
  pg_node_tree = 194,

  /**
   * multivariate ndistinct coefficients
   */
  pg_ndistinct = 3361,

  /**
   * multivariate dependencies
   */
  pg_dependencies = 3402,

  /**
   * char(length), blank-padded string, fixed storage length
   */
  bpchar = 1042,

  /**
   * varchar(length), non-blank-padded string, variable storage length
   */
  varchar = 1043,

  // === Numeric ===

  /**
   * ~18 digit integer, 8-byte storage
   */
  int8 = 20,

  /**
   * -32 thousand to 32 thousand, 2-byte storage
   */
  int2 = 21,

  /**
   * -2 billion to 2 billion integer, 4-byte storage
   */
  int4 = 23,

  /**
   * registered procedure
   */
  regproc = 24,

  /**
   * object identifier(oid), maximum 4 billion
   */
  oid = 26,

  /**
   * single-precision floating point number, 4-byte storage
   */
  float4 = 700,

  /**
   * double-precision floating point number, 8-byte storage
   */
  float8 = 701,

  /**
   * monetary amounts, $d,ddd.cc
   */
  money = 790,

  /**
   * numeric(precision, decimal), arbitrary precision number
   */
  numeric = 1700,

  /**
   * registered procedure (with args)
   */
  regprocedure = 2202,

  /**
   * registered operator
   */
  regoper = 2203,

  /**
   * registered operator (with args)
   */
  regoperator = 2204,

  /**
   * registered class
   */
  regclass = 2205,

  /**
   * registered type
   */
  regtype = 2206,

  /**
   * registered role
   */
  regrole = 4096,

  /**
   * registered namespace
   */
  regnamespace = 4089,

  /**
   * registered text search configuration
   */
  regconfig = 3734,

  /**
   * registered text search dictionary
   */
  regdictionary = 3769,

  // === Array ===

  /**
   * array of int2, used in system tables
   *
   * Array<int2>
   */
  int2vector = 22,

  /**
   * array of oids, used in system tables
   *
   * Array<oid>
   */
  oidvector = 30,

  /**
   * Array<xml>
   */
  _xml = 143,

  /**
   * Array<json>
   */
  _json = 199,

  /**
   * Array<line>
   */
  _line = 629,

  /**
   * Array<circle>
   */
  _circle = 719,

  /**
   * Array<money>
   */
  _money = 791,

  /**
   * Array<bool>
   */
  _bool = 1000,

  /**
   * Array<bytea>
   */
  _bytea = 1001,

  /**
   * Array<char>
   */
  _char = 1002,

  /**
   * Array<name>
   */
  _name = 1003,

  /**
   * Array<int2>
   */
  _int2 = 1005,

  /**
   * Array<int2vector>
   */
  _int2vector = 1006,

  /**
   * Array<int4>
   */
  _int4 = 1007,

  /**
   * Array<regproc>
   */
  _regproc = 1008,

  /**
   * Array<text>
   */
  _text = 1009,

  /**
   * Array<oid>
   */
  _oid = 1028,

  /**
   * Array<tid>
   */
  _tid = 1010,

  /**
   * Array<xid>
   */
  _xid = 1011,

  /**
   * Array<cid>
   */
  _cid = 1012,

  /**
   * Array<oidvector>
   */
  _oidvector = 1013,

  /**
   * Array<bpchar>
   */
  _bpchar = 1014,

  /**
   * Array<varchar>
   */
  _varchar = 1015,

  /**
   * Array<int8>
   */
  _int8 = 1016,

  /**
   * Array<point>
   */
  _point = 1017,

  /**
   * Array<lseg>
   */
  _lseg = 1018,

  /**
   * Array<path>
   */
  _path = 1019,

  /**
   * Array<box>
   */
  _box = 1020,

  /**
   * Array<float4>
   */
  _float4 = 1021,

  /**
   * Array<float8>
   */
  _float8 = 1022,

  /**
   * Array<abstime>
   */
  _abstime = 1023,

  /**
   * Array<reltime>
   */
  _reltime = 1024,

  /**
   * Array<tinterval>
   */
  _tinterval = 1025,

  /**
   * Array<polygon>
   */
  _polygon = 1027,

  /**
   * Array<aclitem>
   */
  _aclitem = 1034,

  /**
   * Array<macaddr>
   */
  _macaddr = 1040,

  /**
   * Array<macaddr8>
   */
  _macaddr8 = 775,

  /**
   * Array<inet>
   */
  _inet = 1041,

  /**
   * Array<cidr>
   */
  _cidr = 651,

  /**
   * Array<cstring>
   */
  _cstring = 1263,

  /**
   * Array<timestamp>
   */
  _timestamp = 1115,

  /**
   * Array<date>
   */
  _date = 1182,

  /**
   * Array<time>
   */
  _time = 1183,

  /**
   * Array<timestamptz>
   */
  _timestamptz = 1185,

  /**
   * Array<interval>
   */
  _interval = 1187,

  /**
   * Array<numeric>
   */
  _numeric = 1231,

  /**
   * Array<timetz>
   */
  _timetz = 1270,

  /**
   * Array<bit>
   */
  _bit = 1561,

  /**
   * Array<varbit>
   */
  _varbit = 1563,

  /**
   * Array<refcursor>
   */
  _refcursor = 2201,

  /**
   * Array<regprocedure>
   */
  _regprocedure = 2207,

  /**
   * Array<regoper>
   */
  _regoper = 2208,

  /**
   * Array<regoperator>
   */
  _regoperator = 2209,

  /**
   * Array<regclass>
   */
  _regclass = 2210,

  /**
   * Array<regtype>
   */
  _regtype = 2211,

  /**
   * Array<regrole>
   */
  _regrole = 4097,

  /**
   * Array<regnamespace>
   */
  _regnamespace = 4090,

  /**
   * Array<uuid>
   */
  _uuid = 2951,

  /**
   * Array<pg_lsn>
   */
  _pg_lsn = 3221,

  /**
   * Array<tsvector>
   */
  _tsvector = 3643,

  /**
   * Array<gtsvector>
   */
  _gtsvector = 3644,

  /**
   * Array<tsquery>
   */
  _tsquery = 3645,

  /**
   * Array<regconfig>
   */
  _regconfig = 3735,

  /**
   * Array<regdictionary>
   */
  _regdictionary = 3770,

  /**
   * Array<jsonb>
   */
  _jsonb = 3807,

  /**
   * Array<txid_snapshot>
   */
  _txid_snapshot = 2949,

  /**
   * Array<int4range>
   */
  _int4range = 3905,

  /**
   * Array<numrange>
   */
  _numrange = 3907,

  /**
   * Array<tsrange>
   */
  _tsrange = 3909,

  /**
   * Array<tstzrange>
   */
  _tstzrange = 3911,

  /**
   * Array<daterange>
   */
  _daterange = 3913,

  /**
   * Array<int8range>
   */
  _int8range = 3927,

  // === Composite ===

  pg_type = 71,

  pg_attribute = 75,

  pg_proc = 81,

  pg_class = 83,

  pg_attrdef = 10000,

  pg_constraint = 10001,

  pg_inherits = 10002,

  pg_index = 10003,

  pg_operator = 10004,

  pg_opfamily = 10005,

  pg_opclass = 10006,

  pg_am = 10130,

  pg_amop = 10131,

  pg_amproc = 10841,

  pg_language = 11253,

  pg_largeobject_metadata = 11254,

  pg_largeobject = 11255,

  pg_aggregate = 11256,

  pg_statistic_ext = 11257,

  pg_statistic = 11258,

  pg_rewrite = 11259,

  pg_trigger = 11260,

  pg_event_trigger = 11261,

  pg_description = 11262,

  pg_cast = 11263,

  pg_enum = 11483,

  pg_namespace = 11484,

  pg_conversion = 11485,

  pg_depend = 11486,

  pg_database = 1248,

  pg_db_role_setting = 11487,

  pg_tablespace = 11488,

  pg_pltemplate = 11489,

  pg_authid = 2842,

  pg_auth_members = 2843,

  pg_shdepend = 11490,

  pg_shdescription = 11491,

  pg_ts_config = 11492,

  pg_ts_config_map = 11493,

  pg_ts_dict = 11494,

  pg_ts_parser = 11495,

  pg_ts_template = 11496,

  pg_extension = 11497,

  pg_foreign_data_wrapper = 11498,

  pg_foreign_server = 11499,

  pg_user_mapping = 11500,

  pg_foreign_table = 11501,

  pg_policy = 11502,

  pg_replication_origin = 11503,

  pg_default_acl = 11504,

  pg_init_privs = 11505,

  pg_seclabel = 11506,

  pg_shseclabel = 4066,

  pg_collation = 11507,

  pg_partitioned_table = 11508,

  pg_range = 11509,

  pg_transform = 11510,

  pg_sequence = 11511,

  pg_publication = 11512,

  pg_publication_rel = 11513,

  pg_subscription = 6101,

  pg_subscription_rel = 11514,

  pg_roles = 11528,

  pg_shadow = 11532,

  pg_group = 11536,

  pg_user = 11539,

  pg_policies = 11542,

  pg_rules = 11546,

  pg_views = 11550,

  pg_tables = 11554,

  pg_matviews = 11558,

  pg_indexes = 11562,

  pg_sequences = 11566,

  pg_stats = 11570,

  pg_publication_tables = 11574,

  pg_locks = 11578,

  pg_cursors = 11581,

  pg_available_extensions = 11584,

  pg_available_extension_versions = 11587,

  pg_prepared_xacts = 11590,

  pg_prepared_statements = 11594,

  pg_seclabels = 11597,

  pg_settings = 11601,

  pg_file_settings = 11606,

  pg_hba_file_rules = 11609,

  pg_timezone_abbrevs = 11612,

  pg_timezone_names = 11615,

  pg_config = 11618,

  pg_stat_all_tables = 11621,

  pg_stat_xact_all_tables = 11625,

  pg_stat_sys_tables = 11629,

  pg_stat_xact_sys_tables = 11633,

  pg_stat_user_tables = 11636,

  pg_stat_xact_user_tables = 11640,

  pg_statio_all_tables = 11643,

  pg_statio_sys_tables = 11647,

  pg_statio_user_tables = 11650,

  pg_stat_all_indexes = 11653,

  pg_stat_sys_indexes = 11657,

  pg_stat_user_indexes = 11660,

  pg_statio_all_indexes = 11663,

  pg_statio_sys_indexes = 11667,

  pg_statio_user_indexes = 11670,

  pg_statio_all_sequences = 11673,

  pg_statio_sys_sequences = 11677,

  pg_statio_user_sequences = 11680,

  pg_stat_activity = 11683,

  pg_stat_replication = 11687,

  pg_stat_wal_receiver = 11691,

  pg_stat_subscription = 11694,

  pg_stat_ssl = 11697,

  pg_replication_slots = 11700,

  pg_stat_database = 11704,

  pg_stat_database_conflicts = 11707,

  pg_stat_user_functions = 11710,

  pg_stat_xact_user_functions = 11714,

  pg_stat_archiver = 11718,

  pg_stat_bgwriter = 11721,

  pg_stat_progress_vacuum = 11724,

  pg_user_mappings = 11728,

  pg_replication_origin_status = 11732,

  // === PseudoTypes ===

  /**
   * internal type for passing CollectedCommand
   */
  pg_ddl_command = 32,

  record = 2249,

  _record = 2287,

  cstring = 2275,

  any = 2276,

  anyarray = 2277,

  void = 2278,

  trigger = 2279,

  event_trigger = 3838,

  language_handler = 2280,

  internal = 2281,

  opaque = 2282,

  anyelement = 2283,

  anynonarray = 2776,

  anyenum = 3500,

  fdw_handler = 3115,

  index_am_handler = 325,

  tsm_handler = 3310,

  anyrange = 3831,

  // === Geometric ===

  /**
   * geometric point '(x, y)'
   */
  point = 600,

  /**
   * geometric line segment '(pt1,pt2)'
   */
  lseg = 601,

  /**
   * geometric path '(pt1,...)'
   */
  path = 602,

  /**
   * geometric box '(lower left,upper right)'
   */
  box = 603,

  /**
   * geometric polygon '(pt1,...)'
   */
  polygon = 604,

  /**
   * geometric line
   */
  line = 628,

  /**
   * geometric circle '(center,radius)'
   */
  circle = 718,

  // === DateTime ===

  /**
   * absolute, limited-range date and time (Unix system time)
   */
  abstime = 702,

  /**
   * date
   */
  date = 1082,

  /**
   * time of day
   */
  time = 1083,

  /**
   * date and time
   */
  timestamp = 1114,

  /**
   * date and time with time zone
   */
  timestamptz = 1184,

  /**
   * time of day with time zone
   */
  timetz = 1266,

  // === Timespan ===

  /**
   * relative, limited-range time interval (Unix delta time)
   */
  reltime = 703,

  /**
   * (abstime,abstime), time interval
   */
  tinterval = 704,

  /**
   * @ <number> <units>, time interval
   */
  interval = 1186,

  // === Unknown ===

  unknown = 705,

  // === NetworkAddress ===

  /**
   * IP address/netmask, host address, netmask optional
   */
  inet = 869,

  /**
   * network IP address/netmask, network address
   */
  cidr = 650,

  // === BitString ===

  /**
   * fixed-length bit string
   */
  bit = 1560,

  /**
   * variable-length bit string
   */
  varbit = 1562,

  // === Range ===

  /**
   * range of integers
   */
  int4range = 3904,

  /**
   * range of numerics
   */
  numrange = 3906,

  /**
   * range of timestamps without time zone
   */
  tsrange = 3908,

  /**
   * range of timestamps with time zone
   */
  tstzrange = 3910,

  /**
   * range of dates
   */
  daterange = 3912,

  /**
   * range of bigints
   */
  int8range = 3926,
}

export default PgDataTypeID;
module.exports = PgDataTypeID;
module.exports.default = PgDataTypeID;
