// auto generated by test suite of pg-schema-introspect

enum PgDataTypeID {
  // === Array ===

  /**
   * Array<abstime>
   */
  _abstime = 1023,

  /**
   * Array<aclitem>
   */
  _aclitem = 1034,

  /**
   * Array<bit>
   */
  _bit = 1561,

  /**
   * Array<bool>
   */
  _bool = 1000,

  /**
   * Array<box>
   */
  _box = 1020,

  /**
   * Array<bpchar>
   */
  _bpchar = 1014,

  /**
   * Array<bytea>
   */
  _bytea = 1001,

  /**
   * Array<char>
   */
  _char = 1002,

  /**
   * Array<cid>
   */
  _cid = 1012,

  /**
   * Array<cidr>
   */
  _cidr = 651,

  /**
   * Array<circle>
   */
  _circle = 719,

  /**
   * Array<cstring>
   */
  _cstring = 1263,

  /**
   * Array<date>
   */
  _date = 1182,

  /**
   * Array<daterange>
   */
  _daterange = 3913,

  /**
   * Array<float4>
   */
  _float4 = 1021,

  /**
   * Array<float8>
   */
  _float8 = 1022,

  /**
   * Array<gtsvector>
   */
  _gtsvector = 3644,

  /**
   * Array<inet>
   */
  _inet = 1041,

  /**
   * Array<int2>
   */
  _int2 = 1005,

  /**
   * Array<int2vector>
   */
  _int2vector = 1006,

  /**
   * Array<int4>
   */
  _int4 = 1007,

  /**
   * Array<int4range>
   */
  _int4range = 3905,

  /**
   * Array<int8>
   */
  _int8 = 1016,

  /**
   * Array<int8range>
   */
  _int8range = 3927,

  /**
   * Array<interval>
   */
  _interval = 1187,

  /**
   * Array<json>
   */
  _json = 199,

  /**
   * Array<jsonb>
   */
  _jsonb = 3807,

  /**
   * Array<jsonpath>
   */
  _jsonpath = 4073,

  /**
   * Array<line>
   */
  _line = 629,

  /**
   * Array<lseg>
   */
  _lseg = 1018,

  /**
   * Array<macaddr>
   */
  _macaddr = 1040,

  /**
   * Array<macaddr8>
   */
  _macaddr8 = 775,

  /**
   * Array<money>
   */
  _money = 791,

  /**
   * Array<name>
   */
  _name = 1003,

  /**
   * Array<numeric>
   */
  _numeric = 1231,

  /**
   * Array<numrange>
   */
  _numrange = 3907,

  /**
   * Array<oid>
   */
  _oid = 1028,

  /**
   * Array<oidvector>
   */
  _oidvector = 1013,

  /**
   * Array<path>
   */
  _path = 1019,

  /**
   * Array<pg_lsn>
   */
  _pg_lsn = 3221,

  /**
   * Array<pg_snapshot>
   */
  _pg_snapshot = 5039,

  /**
   * Array<point>
   */
  _point = 1017,

  /**
   * Array<polygon>
   */
  _polygon = 1027,

  /**
   * Array<refcursor>
   */
  _refcursor = 2201,

  /**
   * Array<regclass>
   */
  _regclass = 2210,

  /**
   * Array<regcollation>
   */
  _regcollation = 4192,

  /**
   * Array<regconfig>
   */
  _regconfig = 3735,

  /**
   * Array<regdictionary>
   */
  _regdictionary = 3770,

  /**
   * Array<regnamespace>
   */
  _regnamespace = 4090,

  /**
   * Array<regoper>
   */
  _regoper = 2208,

  /**
   * Array<regoperator>
   */
  _regoperator = 2209,

  /**
   * Array<regproc>
   */
  _regproc = 1008,

  /**
   * Array<regprocedure>
   */
  _regprocedure = 2207,

  /**
   * Array<regrole>
   */
  _regrole = 4097,

  /**
   * Array<regtype>
   */
  _regtype = 2211,

  /**
   * Array<reltime>
   */
  _reltime = 1024,

  /**
   * Array<text>
   */
  _text = 1009,

  /**
   * Array<tid>
   */
  _tid = 1010,

  /**
   * Array<time>
   */
  _time = 1183,

  /**
   * Array<timestamp>
   */
  _timestamp = 1115,

  /**
   * Array<timestamptz>
   */
  _timestamptz = 1185,

  /**
   * Array<timetz>
   */
  _timetz = 1270,

  /**
   * Array<tinterval>
   */
  _tinterval = 1025,

  /**
   * Array<tsquery>
   */
  _tsquery = 3645,

  /**
   * Array<tsrange>
   */
  _tsrange = 3909,

  /**
   * Array<tstzrange>
   */
  _tstzrange = 3911,

  /**
   * Array<tsvector>
   */
  _tsvector = 3643,

  /**
   * Array<txid_snapshot>
   */
  _txid_snapshot = 2949,

  /**
   * Array<uuid>
   */
  _uuid = 2951,

  /**
   * Array<varbit>
   */
  _varbit = 1563,

  /**
   * Array<varchar>
   */
  _varchar = 1015,

  /**
   * Array<xid>
   */
  _xid = 1011,

  /**
   * Array<xid8>
   */
  _xid8 = 271,

  /**
   * Array<xml>
   */
  _xml = 143,

  /**
   * array of int2, used in system tables
   *
   * Array<int2>
   */
  int2vector = 22,

  /**
   * array of oids, used in system tables
   *
   * Array<oid>
   */
  oidvector = 30,

  // === PseudoTypes ===

  _record = 2287,

  /**
   * pseudo-type representing any type
   */
  any = 2276,

  /**
   * pseudo-type representing a polymorphic array type
   */
  anyarray = 2277,

  /**
   * pseudo-type representing a polymorphic common type
   */
  anycompatible = 5077,

  /**
   * pseudo-type representing an array of polymorphic common type elements
   */
  anycompatiblearray = 5078,

  /**
   * pseudo-type representing a polymorphic common type that is not an array
   */
  anycompatiblenonarray = 5079,

  /**
   * pseudo-type representing a range over a polymorphic common type
   */
  anycompatiblerange = 5080,

  /**
   * pseudo-type representing a polymorphic base type
   */
  anyelement = 2283,

  /**
   * pseudo-type representing a polymorphic base type that is an enum
   */
  anyenum = 3500,

  /**
   * pseudo-type representing a polymorphic base type that is not an array
   */
  anynonarray = 2776,

  /**
   * pseudo-type representing a range over a polymorphic base type
   */
  anyrange = 3831,

  /**
   * C-style string
   */
  cstring = 2275,

  /**
   * pseudo-type for the result of an event trigger function
   */
  event_trigger = 3838,

  /**
   * pseudo-type for the result of an FDW handler function
   */
  fdw_handler = 3115,

  /**
   * pseudo-type for the result of an index AM handler function
   */
  index_am_handler = 325,

  /**
   * pseudo-type representing an internal data structure
   */
  internal = 2281,

  /**
   * pseudo-type for the result of a language handler function
   */
  language_handler = 2280,

  /**
   * obsolete, deprecated pseudo-type
   */
  opaque = 2282,

  /**
   * internal type for passing CollectedCommand
   */
  pg_ddl_command = 32,

  /**
   * pseudo-type representing any composite type
   */
  record = 2249,

  table_am_handler = 269,

  /**
   * pseudo-type for the result of a trigger function
   */
  trigger = 2279,

  /**
   * pseudo-type for the result of a tablesample method function
   */
  tsm_handler = 3310,

  /**
   * pseudo-type for the result of a function with no real result
   */
  void = 2278,

  // === DateTime ===

  /**
   * absolute, limited-range date and time (Unix system time)
   */
  abstime = 702,

  /**
   * date
   */
  date = 1082,

  /**
   * time of day
   */
  time = 1083,

  /**
   * date and time
   */
  timestamp = 1114,

  /**
   * date and time with time zone
   */
  timestamptz = 1184,

  /**
   * time of day with time zone
   */
  timetz = 1266,

  // === UserDefined ===

  /**
   * access control list
   */
  aclitem = 1033,

  /**
   * variable-length string, binary values escaped
   */
  bytea = 17,

  /**
   * command identifier type, sequence in transaction id
   */
  cid = 29,

  /**
   * GiST index internal text representation for text search
   */
  gtsvector = 3642,

  /**
   * JSON stored as text
   */
  json = 114,

  /**
   * Binary JSON
   */
  jsonb = 3802,

  /**
   * JSON path
   */
  jsonpath = 4072,

  /**
   * XX:XX:XX:XX:XX:XX, MAC address
   */
  macaddr = 829,

  /**
   * XX:XX:XX:XX:XX:XX:XX:XX, MAC address
   */
  macaddr8 = 774,

  /**
   * PostgreSQL LSN datatype
   */
  pg_lsn = 3220,

  /**
   * snapshot
   */
  pg_snapshot = 5038,

  /**
   * reference to cursor (portal name)
   */
  refcursor = 1790,

  /**
   * storage manager
   */
  smgr = 210,

  /**
   * (block, offset), physical location of tuple
   */
  tid = 27,

  /**
   * query representation for text search
   */
  tsquery = 3615,

  /**
   * text representation for text search
   */
  tsvector = 3614,

  /**
   * txid snapshot
   */
  txid_snapshot = 2970,

  /**
   * UUID datatype
   */
  uuid = 2950,

  /**
   * transaction id
   */
  xid = 28,

  /**
   * full transaction id
   */
  xid8 = 5069,

  /**
   * XML content
   */
  xml = 142,

  // === BitString ===

  /**
   * fixed-length bit string
   */
  bit = 1560,

  /**
   * variable-length bit string
   */
  varbit = 1562,

  // === Boolean ===

  /**
   * boolean, 'true'/'false'
   */
  bool = 16,

  // === Geometric ===

  /**
   * geometric box '(lower left,upper right)'
   */
  box = 603,

  /**
   * geometric circle '(center,radius)'
   */
  circle = 718,

  /**
   * geometric line
   */
  line = 628,

  /**
   * geometric line segment '(pt1,pt2)'
   */
  lseg = 601,

  /**
   * geometric path '(pt1,...)'
   */
  path = 602,

  /**
   * geometric point '(x, y)'
   */
  point = 600,

  /**
   * geometric polygon '(pt1,...)'
   */
  polygon = 604,

  // === String ===

  /**
   * char(length), blank-padded string, fixed storage length
   */
  bpchar = 1042,

  /**
   * single character
   */
  char = 18,

  /**
   * 63-byte type for storing system identifiers
   */
  name = 19,

  /**
   * multivariate dependencies
   */
  pg_dependencies = 3402,

  /**
   * multivariate MCV list
   */
  pg_mcv_list = 5017,

  /**
   * multivariate ndistinct coefficients
   */
  pg_ndistinct = 3361,

  /**
   * string representing an internal node tree
   */
  pg_node_tree = 194,

  /**
   * variable-length string, no limit specified
   */
  text = 25,

  /**
   * varchar(length), non-blank-padded string, variable storage length
   */
  varchar = 1043,

  // === NetworkAddress ===

  /**
   * network IP address/netmask, network address
   */
  cidr = 650,

  /**
   * IP address/netmask, host address, netmask optional
   */
  inet = 869,

  // === Range ===

  /**
   * range of dates
   */
  daterange = 3912,

  /**
   * range of integers
   */
  int4range = 3904,

  /**
   * range of bigints
   */
  int8range = 3926,

  /**
   * range of numerics
   */
  numrange = 3906,

  /**
   * range of timestamps without time zone
   */
  tsrange = 3908,

  /**
   * range of timestamps with time zone
   */
  tstzrange = 3910,

  // === Numeric ===

  /**
   * single-precision floating point number, 4-byte storage
   */
  float4 = 700,

  /**
   * double-precision floating point number, 8-byte storage
   */
  float8 = 701,

  /**
   * -32 thousand to 32 thousand, 2-byte storage
   */
  int2 = 21,

  /**
   * -2 billion to 2 billion integer, 4-byte storage
   */
  int4 = 23,

  /**
   * ~18 digit integer, 8-byte storage
   */
  int8 = 20,

  /**
   * monetary amounts, $d,ddd.cc
   */
  money = 790,

  /**
   * numeric(precision, decimal), arbitrary precision number
   */
  numeric = 1700,

  /**
   * object identifier(oid), maximum 4 billion
   */
  oid = 26,

  /**
   * registered class
   */
  regclass = 2205,

  /**
   * registered collation
   */
  regcollation = 4191,

  /**
   * registered text search configuration
   */
  regconfig = 3734,

  /**
   * registered text search dictionary
   */
  regdictionary = 3769,

  /**
   * registered namespace
   */
  regnamespace = 4089,

  /**
   * registered operator
   */
  regoper = 2203,

  /**
   * registered operator (with args)
   */
  regoperator = 2204,

  /**
   * registered procedure
   */
  regproc = 24,

  /**
   * registered procedure (with args)
   */
  regprocedure = 2202,

  /**
   * registered role
   */
  regrole = 4096,

  /**
   * registered type
   */
  regtype = 2206,

  // === Timespan ===

  /**
   * @ <number> <units>, time interval
   */
  interval = 1186,

  /**
   * relative, limited-range time interval (Unix delta time)
   */
  reltime = 703,

  /**
   * (abstime,abstime), time interval
   */
  tinterval = 704,

  // === Composite ===

  pg_aggregate = 12013,

  pg_am = 12007,

  pg_amop = 12008,

  pg_amproc = 12009,

  pg_attrdef = 12000,

  pg_attribute = 75,

  pg_auth_members = 2843,

  pg_authid = 2842,

  pg_available_extension_versions = 12151,

  pg_available_extension_versions = 12153,

  pg_available_extensions = 12148,

  pg_available_extensions = 12150,

  pg_cast = 12021,

  pg_class = 83,

  pg_collation = 12045,

  pg_config = 12183,

  pg_config = 12184,

  pg_constraint = 12001,

  pg_conversion = 12024,

  pg_cursors = 12145,

  pg_cursors = 12147,

  pg_database = 1248,

  pg_db_role_setting = 12026,

  pg_default_acl = 12042,

  pg_depend = 12025,

  pg_description = 12020,

  pg_enum = 12022,

  pg_event_trigger = 12019,

  pg_extension = 12035,

  pg_file_settings = 12171,

  pg_file_settings = 12172,

  pg_foreign_data_wrapper = 12036,

  pg_foreign_server = 12037,

  pg_foreign_table = 12039,

  pg_group = 12096,

  pg_group = 12098,

  pg_hba_file_rules = 12174,

  pg_hba_file_rules = 12175,

  pg_index = 12003,

  pg_indexes = 12122,

  pg_indexes = 12124,

  pg_inherits = 12002,

  pg_init_privs = 12043,

  pg_language = 12010,

  pg_largeobject = 12012,

  pg_largeobject_metadata = 12011,

  pg_locks = 12142,

  pg_locks = 12144,

  pg_matviews = 12118,

  pg_matviews = 12120,

  pg_namespace = 12023,

  pg_opclass = 12006,

  pg_operator = 12004,

  pg_opfamily = 12005,

  pg_partitioned_table = 12046,

  pg_policies = 12102,

  pg_policies = 12104,

  pg_policy = 12040,

  pg_prepared_statements = 12159,

  pg_prepared_statements = 12160,

  pg_prepared_xacts = 12155,

  pg_prepared_xacts = 12156,

  pg_proc = 81,

  pg_publication = 12050,

  pg_publication_rel = 12051,

  pg_publication_tables = 12138,

  pg_publication_tables = 12140,

  pg_range = 12047,

  pg_replication_origin = 12041,

  pg_replication_origin_status = 12323,

  pg_replication_origin_status = 12310,

  pg_replication_slots = 12274,

  pg_replication_slots = 12269,

  pg_rewrite = 12017,

  pg_roles = 12088,

  pg_roles = 12090,

  pg_rules = 12106,

  pg_rules = 12108,

  pg_seclabel = 12044,

  pg_seclabels = 12162,

  pg_seclabels = 12163,

  pg_sequence = 12049,

  pg_sequences = 12126,

  pg_sequences = 12128,

  pg_settings = 12166,

  pg_settings = 12167,

  pg_shadow = 12092,

  pg_shadow = 12094,

  pg_shdepend = 12028,

  pg_shdescription = 12029,

  pg_shmem_allocations = 12186,

  pg_shseclabel = 4066,

  pg_stat_activity = 12251,

  pg_stat_activity = 12249,

  pg_stat_all_indexes = 12221,

  pg_stat_all_indexes = 12219,

  pg_stat_all_tables = 12189,

  pg_stat_all_tables = 12187,

  pg_stat_archiver = 12293,

  pg_stat_archiver = 12288,

  pg_stat_bgwriter = 12296,

  pg_stat_bgwriter = 12291,

  pg_stat_database = 12278,

  pg_stat_database = 12273,

  pg_stat_database_conflicts = 12282,

  pg_stat_database_conflicts = 12277,

  pg_stat_gssapi = 12271,

  pg_stat_gssapi = 12266,

  pg_stat_progress_analyze = 12299,

  pg_stat_progress_basebackup = 12315,

  pg_stat_progress_cluster = 12307,

  pg_stat_progress_cluster = 12298,

  pg_stat_progress_create_index = 12311,

  pg_stat_progress_create_index = 12302,

  pg_stat_progress_vacuum = 12303,

  pg_stat_progress_vacuum = 12294,

  pg_stat_replication = 12255,

  pg_stat_replication = 12253,

  pg_stat_slru = 12259,

  pg_stat_ssl = 12268,

  pg_stat_ssl = 12263,

  pg_stat_subscription = 12265,

  pg_stat_subscription = 12260,

  pg_stat_sys_indexes = 12225,

  pg_stat_sys_indexes = 12223,

  pg_stat_sys_tables = 12197,

  pg_stat_sys_tables = 12195,

  pg_stat_user_functions = 12285,

  pg_stat_user_functions = 12280,

  pg_stat_user_indexes = 12228,

  pg_stat_user_indexes = 12226,

  pg_stat_user_tables = 12204,

  pg_stat_user_tables = 12202,

  pg_stat_wal_receiver = 12262,

  pg_stat_wal_receiver = 12257,

  pg_stat_xact_all_tables = 12193,

  pg_stat_xact_all_tables = 12191,

  pg_stat_xact_sys_tables = 12201,

  pg_stat_xact_sys_tables = 12199,

  pg_stat_xact_user_functions = 12289,

  pg_stat_xact_user_functions = 12284,

  pg_stat_xact_user_tables = 12208,

  pg_stat_xact_user_tables = 12206,

  pg_statio_all_indexes = 12231,

  pg_statio_all_indexes = 12229,

  pg_statio_all_sequences = 12241,

  pg_statio_all_sequences = 12239,

  pg_statio_all_tables = 12211,

  pg_statio_all_tables = 12209,

  pg_statio_sys_indexes = 12235,

  pg_statio_sys_indexes = 12233,

  pg_statio_sys_sequences = 12245,

  pg_statio_sys_sequences = 12243,

  pg_statio_sys_tables = 12215,

  pg_statio_sys_tables = 12213,

  pg_statio_user_indexes = 12238,

  pg_statio_user_indexes = 12236,

  pg_statio_user_sequences = 12248,

  pg_statio_user_sequences = 12246,

  pg_statio_user_tables = 12218,

  pg_statio_user_tables = 12216,

  pg_statistic = 12016,

  pg_statistic_ext = 12014,

  pg_statistic_ext_data = 12015,

  pg_stats = 12130,

  pg_stats = 12132,

  pg_stats_ext = 12134,

  pg_stats_ext = 12136,

  pg_subscription = 6101,

  pg_subscription_rel = 12052,

  pg_subscription_rel = 12053,

  pg_tables = 12114,

  pg_tables = 12116,

  pg_tablespace = 12027,

  pg_timezone_abbrevs = 12177,

  pg_timezone_abbrevs = 12178,

  pg_timezone_names = 12180,

  pg_timezone_names = 12181,

  pg_transform = 12048,

  pg_trigger = 12018,

  pg_ts_config = 12030,

  pg_ts_config_map = 12031,

  pg_ts_dict = 12032,

  pg_ts_parser = 12033,

  pg_ts_template = 12034,

  pg_type = 71,

  pg_user = 12099,

  pg_user = 12101,

  pg_user_mapping = 12038,

  pg_user_mappings = 12319,

  pg_user_mappings = 12306,

  pg_views = 12110,

  pg_views = 12112,

  // === Unknown ===

  /**
   * pseudo-type representing an undetermined type
   */
  unknown = 705,
}

export default PgDataTypeID;
module.exports = PgDataTypeID;
module.exports.default = PgDataTypeID;
