/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: cbXRsRyXDxd4OSCHLtIlYydYhde6O6dDJA1NhRqefSlomoGe60vzsB5bgLbhv5AyIMXjcjUE4ZeBekvWUi//CA==
 */

/* eslint-disable */
// tslint:disable

interface PartitionedP0 {
  create_date: Date;
  id: number;
}
export default PartitionedP0;

interface PartitionedP0_InsertParameters {
  create_date: Date;
  id: number;
}
export type {PartitionedP0_InsertParameters};
