/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: IoAQqBdHSQ9UUcEcMwJBCQUnaycfMMjacdu+UAT9oyDqDbmRXop9aLcd69DKxiu7vXmkkzt8DXJRxqot2lNG3g==
 */

/* eslint-disable */
// tslint:disable

interface PartitionedP1 {
  create_date: Date;
  id: number;
}
export default PartitionedP1;

interface PartitionedP1_InsertParameters {
  create_date: Date;
  id: number;
}
export type {PartitionedP1_InsertParameters};
