/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: rWQV4EcYxZrGCqVcYgt89yqljDZ4SmUTv0HH6WBAQ2ACc4Tc+bs64Sx+V65nJO1nVF/Cerd9VPvrv+iohoV3pA==
 */

/* eslint-disable */
// tslint:disable

interface Partitioned {
  create_date: Date;
  id: number;
}
export default Partitioned;

interface Partitioned_InsertParameters {
  create_date: Date;
  id: number;
}
export type {Partitioned_InsertParameters};
