/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: K/dbF6GpS/sJOcHd41i/b22GcYWCRG+pWEcYTq+x6YsUoT2z/tytLraiFRXpnELcNmFHDkQ2sGkzbXDpSgFFqg==
 */

// eslint:disable
// tslint:disable

import User from './users'

  /**
   * This is a great table
   */
interface Photo {
  caption: (string) | null
  cdn_url: string & {__brand?: "url"}
  /**
   * @default nextval('print_types.photos_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'photos_id'}
  metadata: unknown
  owner_user_id: User['id']
}
export default Photo;

  /**
   * This is a great table
   */
interface Photos_InsertParameters {
  caption?: (string) | null
  cdn_url: string & {__brand?: "url"}
  /**
   * @default nextval('print_types.photos_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'photos_id'}
  metadata: unknown
  owner_user_id: User['id']
}
export {Photos_InsertParameters}
