/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: RaxnJplurntBTC0aUsQPE668GzCYbEs1e3mzJNCfVEd01+oIYkxGUG6sKyRB/W3rsxGishnyNbr3rN5x5IInSw==
 */

/* eslint-disable */
// tslint:disable

import User from './users';

/**
 * This is a great table
 */
interface Photo {
  caption: string | null;
  cdn_url: string & {__brand?: 'url'};
  created_at: Date | null;
  /**
   * @default nextval('print_types.photos_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'photos_id'};
  metadata: unknown;
  owner_user_id: User['id'];
  updated_at: Date | null;
}
export default Photo;

/**
 * This is a great table
 */
interface Photos_InsertParameters {
  caption?: string | null;
  cdn_url: string & {__brand?: 'url'};
  created_at?: Date | null;
  /**
   * @default nextval('print_types.photos_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'photos_id'};
  metadata: unknown;
  owner_user_id: User['id'];
  updated_at?: Date | null;
}
export type {Photos_InsertParameters};
