/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 3d+bC7PldcIEpJmzeYhbek/hkK8hvozwMC69UX92lcfqSQElC58qGX2qSWny6TYFBSJVWOhGk27t+7T2GP1l/A==
 */

// eslint:disable
// tslint:disable

interface User {
  age: number | null;
  bio: string | null;
  id: number & {readonly __brand?: 'users_id'};
  screen_name: string;
}
export default User;

interface Users_InsertParameters {
  age?: number | null;
  bio?: string | null;
  id?: number & {readonly __brand?: 'users_id'};
  screen_name: string;
}
export {Users_InsertParameters};
