/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: j+3qGf2A7qh66mBdMgbG2zm2tS4/9DZvvpuPV6hggsfbAJIDjB7we0FoYOGNdZ0W+dltixV1QPj6Odx503aykA==
 */

/* eslint-disable */
// tslint:disable

interface User {
  age: number | null;
  bio: string | null;
  created_at: Date | null;
  /**
   * @default nextval('print_types.users_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'users_id'};
  screen_name: string;
  updated_at: Date | null;
}
export default User;

interface Users_InsertParameters {
  age?: number | null;
  bio?: string | null;
  created_at?: Date | null;
  /**
   * @default nextval('print_types.users_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'users_id'};
  screen_name: string;
  updated_at?: Date | null;
}
export type {Users_InsertParameters};
