/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: l7Etfd+47JJSrEmdVGuWJViLxPNQvojKQ53hD4WDgcipF2GUyrPfpf8LgNzSMtLdUIO0hxNLqlYi17Vwn5fm9A==
 */

// eslint:disable
// tslint:disable

interface User {
  age: number | null;
  bio: string | null;
  /**
   * @default nextval('print_types.users_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'users_id'};
  screen_name: string;
}
export default User;

interface Users_InsertParameters {
  age?: number | null;
  bio?: string | null;
  /**
   * @default nextval('print_types.users_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'users_id'};
  screen_name: string;
}
export {Users_InsertParameters};
